jobs:
- job: Build
  pool:
    vmImage: 'vs2017-win2016'
  timeoutInMinutes: 240
  steps:
  - script: |
      choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
      choco upgrade %ROS_METAPACKAGE% -y
      echo Apply hot-fix from https://github.com/ms-iot/catkin/pull/24
      powershell -Command "Invoke-WebRequest -OutFile C:\opt\ros\melodic\x64\bin\catkin_make_isolated https://raw.githubusercontent.com/ros/catkin/e98ee68d675f0ce6ad6297346743623f72f4da05/bin/catkin_make_isolated"
      echo Apply hot-fix from https://github.com/ms-iot/catkin/pull/25
      powershell -Command "Invoke-WebRequest -OutFile C:\opt\ros\melodic\x64\share\catkin\cmake\catkin_package.cmake https://raw.githubusercontent.com/ros/catkin/f84dd870e6c1236c3e104b7c288128517485d948/cmake/catkin_package.cmake"
      robocopy "." ".\src\cartographer" /E /MOVE /XD "src" > NUL
      call "C:\opt\ros\melodic\x64\env.bat" rosdep install --from-paths src --ignore-src -r -y
    env:
      ROS_METAPACKAGE: 'ros-melodic-desktop'
    displayName: Install prerequisites

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\setup.bat"
      set PATH=%PATH:C:\tools\mingw64\bin;=%
      set PATH=%PATH:C:\Program Files\Git\bin;=%
      set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
      set PATH=%PATH:C:\Program Files\Git\mingw64\bin;=%
      catkin_make_isolated --use-ninja --install
    displayName: Build

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\setup.bat"
      set PATH=%PATH:C:\tools\mingw64\bin;=%
      set PATH=%PATH:C:\Program Files\Git\bin;=%
      set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
      set PATH=%PATH:C:\Program Files\Git\mingw64\bin;=%
      cd build_isolated\cartographer\install & ctest --no-compress-output -T Test
    displayName: Run tests

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\setup.bat"
      set PATH=%PATH:C:\tools\mingw64\bin;=%
      set PATH=%PATH:C:\Program Files\Git\bin;=%
      set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
      set PATH=%PATH:C:\Program Files\Git\mingw64\bin;=%
      python src\cartographer\scripts\ctest_to_junit.py build_isolated\cartographer\install
    displayName: Convert tests to jUnit
    condition: always()

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testRunner: 'jUnit'
      testResultsFiles: '**\jUnit.xml'
      searchFolder: '$(Build.SourcesDirectory)\build_isolated\cartographer\install\Testing'
    condition: always()