# Copyright 2018 The Cartographer Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

jobs:
- job: Build
  pool:
    vmImage: 'vs2017-win2016'
  timeoutInMinutes: 360
  steps:
  - script: |
      choco sources add -n=roswin -s https://roswin.azurewebsites.net/api/v2/ --priority 1
      rem Azure VM runs out of space on C:, so use D: for ros and rosdeps
      mkdir D:\opt && mklink /J C:\opt D:\opt
      choco upgrade %ROS_METAPACKAGE% -y
      echo Apply hot-fix from https://github.com/ms-iot/catkin/pull/25
      powershell -Command "Invoke-WebRequest -OutFile C:\opt\ros\melodic\x64\share\catkin\cmake\catkin_package.cmake https://raw.githubusercontent.com/ros/catkin/f84dd870e6c1236c3e104b7c288128517485d948/cmake/catkin_package.cmake"
      robocopy "." ".\src\cartographer" /E /MOVE /XD "src" > NUL
      call "C:\opt\ros\melodic\x64\env.bat" rosdep install --from-paths src --ignore-src -r -y
    env:
      ROS_METAPACKAGE: 'ros-melodic-desktop'
    displayName: Install prerequisites

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\setup.bat"
      call src\cartographer\scripts\remove_mingw_cygwin_from_path.bat
      catkin_make_isolated --use-ninja --install
    displayName: Build

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\setup.bat"
      call src\cartographer\scripts\remove_mingw_cygwin_from_path.bat
      cd build_isolated\cartographer\install && ctest --no-compress-output -T Test
    displayName: Run tests

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call "C:\opt\ros\melodic\x64\setup.bat"
      call src\cartographer\scripts\remove_mingw_cygwin_from_path.bat
      python src\cartographer\scripts\ctest_to_junit.py build_isolated\cartographer\install
    displayName: Convert tests to jUnit
    condition: always()

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testRunner: 'jUnit'
      testResultsFiles: '**\jUnit.xml'
      searchFolder: '$(Build.SourcesDirectory)\build_isolated\cartographer\install\Testing'
    condition: always()