version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/thirdwave
    steps:
      - run:
          name: Authenticate Google Cloud.
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet auth configure-docker
      - checkout
      - run:
          name: Install dependencies.
          command: |
            apt-get install -y \
              python-pip
            pip install \
              docker-compose==1.23.0
      - setup_remote_docker
      - run:
          name: Pull docker images.
          command: |
            set +o pipefail
            docker pull us.gcr.io/voltaic-day-213421/base
            docker pull us.gcr.io/voltaic-day-213421/devel
            docker pull us.gcr.io/voltaic-day-213421/deploy
      - run:
          name: Tag deploy docker image as bazel to allow use of bazel caching.
          command: |
            set +o pipefail
            docker tag us.gcr.io/voltaic-day-213421/deploy us.gcr.io/voltaic-day-213421/bazel || true
      - add_ssh_keys:
          fingerprints:
            - "3f:de:c2:39:e2:48:3f:08:f5:79:3e:b0:32:8f:8f:11"
      - run:
          name: Build base image.
          command: |
            docker build --cache-from=us.gcr.io/voltaic-day-213421/base -t us.gcr.io/voltaic-day-213421/base --file ./docker/base/Dockerfile .
      - run:
          name: Build devel image.
          command: |
            docker build --cache-from=us.gcr.io/voltaic-day-213421/devel -t us.gcr.io/voltaic-day-213421/devel --file ./docker/devel/Dockerfile .
      - run:
          name: Build deployment image.
          command: |
            cp ${HOME}/.ssh/id_rsa_3fdec239e2483f08f5793eb0328f8f11 ~/thirdwave/id_rsa
            docker build \
              --cache-from=us.gcr.io/voltaic-day-213421/deploy \
              --cache-from=us.gcr.io/voltaic-day-213421/bazel \
              -t us.gcr.io/voltaic-day-213421/deploy \
              --file ./docker/deployment/Dockerfile .
            rm ~/thirdwave/id_rsa
      - run:
          name: Run linter and tests.
          command: |
            set -e
            docker run us.gcr.io/voltaic-day-213421/deploy ./tools/linter.sh
            docker run us.gcr.io/voltaic-day-213421/deploy bazel test --test_output=all //...
      - run:
          name: Push docker images (only on master).
          command: |
            set +o pipefail 
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push us.gcr.io/voltaic-day-213421/base
              docker push us.gcr.io/voltaic-day-213421/devel
              docker push us.gcr.io/voltaic-day-213421/deploy
            fi
