name: Ubuntu 22.04 CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Run the Dockerfile
          run: docker build . -f Dockerfile.jammy
